apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: immigration-messages
  namespace: global
  description: Immigration messages App
  annotations:
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=immigration"
    backstage.io/techdocs-ref: dir:.
  tags:
   - global
   - uscis
   - demo
  links:
    - url: https://www.uscis.gov/
      title: USCIS Home
      icon: language
spec:
  type: service
  lifecycle: production
  owner: global-team
  system: immigration