apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: immigration-messages
    apps.tanzu.vmware.com/workload-type: test
    carto.run/workload-name: immigration-messages
    kapp.k14s.io/app: "1693591233015193143"
  name: immigration-messages-loadbalancer
  namespace: global
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
status:
  loadBalancer: {}
