apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: immigration-messages
  labels:
    apps.tanzu.vmware.com/workload-type: test
    app.kubernetes.io/part-of: immigration-messages
spec:
  params:
  - name: probes
    value: 
      livenessProbe: {"httpGet":{"path":"/","port":3000},"initialDelaySeconds":20,"periodSeconds":10}
      readinessProbe: {"httpGet":{"path":"/","port":3000},"initialDelaySeconds":20,"periodSeconds":10}
  - name: ports
    value: {"containerPort": 3000, "port": 80, "name": "http"}
  - name: clusterBuilder
    value: full-jammy
  serviceClaims:
   - name: postgresql-rails-7-demo
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: postgresql-rails-7-demo
   - name: redis-rails-7-demo
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: redis-rails-7-demo
  env:
   - name: SECRET_KEY_BASE
     valueFrom:
       secretKeyRef:
         name: rails-secret-key-trev-cluster
         key: SECRET_KEY_BASE
  source:
    git:      
      url: https://github.com/trevorputbrese/rails-7-demo
      ref:
        branch: main