apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: immigration-messages
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: immigration-messages
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: ruby-rails
  - name: clusterBuilder
    value: full-jammy
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
   - name: postgresql-rails-7-demo
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: postgresql-rails-7-demo
   - name: redis-rails-7-demo
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: redis-rails-7-demo
  env:
   - name: SECRET_KEY_BASE
     value: some-secret-key-base
  source:
    git:      
      url: https://github.com/trevorputbrese/rails-7-demo
      ref:
        branch: main